trigger:
- master

pool:
  vmImage: Ubuntu-16.04

variables:
  imageName: azure-pipelines-canary-k8s
  dockerRegistryServiceConnection: bkdocker #replace with name of your Docker registry service connection
  imageRepository: 'azure-pipelines-canary-k8s'
  containerRegistry: containerRegistry #replace with the name of your container registry, Should be in the format foobar.azurecr.io
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: Ubuntu-16.04
    steps:
    - task: Docker@2
      displayName: Build and push image
      inputs:
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(imageName)
        command: buildAndPush
        Dockerfile: app/Dockerfile
        tags: |
          $(tag)

    - upload: manifests
      artifact: manifests

    - upload: misc
      artifact: misc